name: PHPRETS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version:
            - 8.2
            - 8.3
            - 8.4
    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP with composer v2
      uses: shivammathur/setup-php@v2
      with:
         php-version: ${{ matrix.php_version }}
         coverage: pcov
         extensions: json, simplexml
         tools: composer:v2
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php_version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php_version }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-progress

    - name: Static analysis
      run: composer run-script stan

    - name: Run test suite
      run: composer run-script test
